### PR TITLE
fixed issue where request header where not match when they should

### PR DESCRIPTION
**Pull request by ryanzec**
I switched the request headers match to use isEqual instead of contains as I don’t think contains is the right choice here (can was not properly showing matched header when they were the same).

### CODE REVIEW

**Comment by callmehiphop** [comment]
The problem with isEqual is that some third party libraries (jQuery, etc.) will add additional headers to your request. Maybe we should add another option called strict (or fuzzy!) that will dictate how we match headers.

**Comment by ryanzec** [comment]
Well contains does not work at all.  If you do:

```javascript
//effectively what the current code is doing
_.contains({'Content-Type':'application/json'},{'Content-Type':'application/json'})
```

That returns false which means it does not work with request headers right now.

I don't think a strict mode is needed.  I have updated the code so that when matching a mock, it makes sure that at least the headers in the mock are in the headers of the request it is checking against.

**Comment by callmehiphop** [comment]
Is there a different lodash function that'll work? I was looking at matches and seems like it would fit the bill

https://lodash.com/docs#matches

**Comment by stephenplusplus** [comment]
https://lodash.com/docs#isMatch

**Comment by ryanzec** [comment]
I'll give that a try tonight.

**Comment by ryanzec** [comment]
Ok I have updated it to use `isMatch()` which seems to work.  I also updated the custom build of lodash (which did not have isMatch).

I squash the commits down to one.

**Comment by ryanzec** [comment]
How does the new version look?

**Comment by stephenplusplus** [comment]
LGTM. It would be great if you could add a test as well.

**Pull request merged**
